// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwjIAa-tNgqdh75DUwdd3A8g60MNKp0zU',
    appId: '1:903984955018:web:9058f6fbdaafd14bfc7773',
    messagingSenderId: '903984955018',
    projectId: 'scalp-smart-pbl-project',
    authDomain: 'scalp-smart-pbl-project.firebaseapp.com',
    storageBucket: 'scalp-smart-pbl-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhX334pGZ7nTM2dKoH_I0uf5FTNfsh6k',
    appId: '1:903984955018:android:8005dd0eb67ae3bffc7773',
    messagingSenderId: '903984955018',
    projectId: 'scalp-smart-pbl-project',
    storageBucket: 'scalp-smart-pbl-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Xl7U-BrGhVHnzhn66Oxm3OAX4K3wt3E',
    appId: '1:903984955018:ios:0c8ced53d12c2f2dfc7773',
    messagingSenderId: '903984955018',
    projectId: 'scalp-smart-pbl-project',
    storageBucket: 'scalp-smart-pbl-project.appspot.com',
    iosBundleId: 'com.example.scalpSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Xl7U-BrGhVHnzhn66Oxm3OAX4K3wt3E',
    appId: '1:903984955018:ios:fd92c2797f4ecbd8fc7773',
    messagingSenderId: '903984955018',
    projectId: 'scalp-smart-pbl-project',
    storageBucket: 'scalp-smart-pbl-project.appspot.com',
    iosBundleId: 'com.example.scalpSmart.RunnerTests',
  );
}
