final products = [
  {
    "id" : "1",
    "name" : "Ravel Hair Fall Control Shampoo",
    "price" : "₹ 999",
    "brand" : "Ravel Shampoo",
    "image" : "https://m.media-amazon.com/images/I/61vXWiRxtgL._SX425_PIbundle-2,TopRight,0,0_AA425SH20_.jpg",
    "Description" : "CUSTOMISED HAIR CARE REGIMEN TO SUIT DRY SCALP & WAVY HAIR: Safe and effective hair care regimen for dry scalp & wavy hair with hair fall. Includes a set of 2 products - Shampoo & Conditioner 200ml each; Reduces hair fall within 2-3 weeks.",
    "benefits" : "Anti-frizz,Breakage,Deep Conditioning,Hydrating,Moisturizing,Nourishing,Softening,Strengthening",
    "url" : "https://www.amazon.in/Ravel-Customized-Strengthen-Products-Conditioner/dp/B0BFL4H1ZK/ref=sr_1_6?crid=2SOOVUCQ6Q6J4&keywords=products%2Bhair%2Bshampoo&qid=1707148642&sprefix=products%2Bhair%2Bshampoo%2Caps%2C193&sr=8-6&th=1",
    "category" : "Hairfall",
    "best seller" : "true",
  },
  {
    "id" : "2",
    "name" : "Fytika Anti Dandruff Hair Cleanser",
    "price" : "₹ 349",
    "brand" : "Fytica Shampoo",
    "image" : "https://m.media-amazon.com/images/I/61alCtIwtKL._SX425_.jpg",
    "Description" : "Potent Dandruff Solution: Infused with Orange Peel Extract, Neem, Amla, Reetha, and Aloe Vera extracts, this specialised formula effectively combats dandruff-causing bacteria while soothing the scalp, granting relief from flaky scalp conditions.",
    "benefits" : "Soothing Hydration: Experience the enchantment of Aloe Vera Extract, offering calming hydration to the scalp and reducing scalp irritation for a comfortable cleansing experience.",
    "url" : "https://www.amazon.in/dp/B0CFVCVHFR/ref=sspa_dk_detail_5?psc=1&pd_rd_i=B0CFVCVHFR&pd_rd_w=7lWj6&content-id=amzn1.sym.dcd65529-2e56-4c74-bf19-15db07b4a1fc&pf_rd_p=dcd65529-2e56-4c74-bf19-15db07b4a1fc&pf_rd_r=J1NFTE4BBQMBNPF7P9ZF&pd_rd_wg=FMOUa&pd_rd_r=92e82ca1-3524-4d38-895a-999e4e932e68&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWxfdGhlbWF0aWM",
    "category" : "Dandruff",
    "best seller" : "false",
  },
  {
    "id" : "3",
    "name" : "Man Matters Hair Growth Pack",
    "price" : "₹ 899",
    "brand" : "Man Matters",
    "image" : "https://i.mscwlns.co/media/misc/pdp_rcl/26166729/stage_2_new_XLIUWiEoU.png?tr=w-800",
    "Description" : "CUSTOMISED HAIR CARE REGIMEN TO SUIT DRY SCALP & WAVY HAIR: Safe and effective hair care regimen for dry scalp & wavy hair with hair fall. Includes a set of 2 products - Shampoo & Conditioner 200ml each; Reduces hair fall within 2-3 weeks.",
    "benefits" : "Anti-frizz,Breakage,Deep Conditioning,Hydrating,Moisturizing,Nourishing,Softening,Strengthening",
    "url" : "https://manmatters.com/dp/26166729",
    "category" : "Volumize",
    "best seller" : "true",
  },
  {
    "id" : "4",
    "name" : "Khadi Natural Bhringraj Shampoo",
    "price" : "₹ 158",
    "brand" : "Khadi Shampoo",
    "image" : "https://m.media-amazon.com/images/I/41NHBKgWZiL._SX300_SY300_QL70_FMwebp_.jpg",
    "Description" : "Hair Growth is not a Dream anymore: A hair care recipe that is years old will produce outstanding effects and encourage hair growth. Increased hair growth results from the oils in the shampoo penetrating deeply into the roots and stimulating the hair follicles.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Khadi-Natural-Bhringraj-Shampoo-Cleanser/dp/B01N3YESMI/ref=sr_1_7?crid=24QDKNVQGNX8A&keywords=shampoo&qid=1707157301&s=beauty&sprefix=shampoo%2Cbeauty%2C194&sr=1-7&th=1",
    "category" : "Hairfall",
    "best seller" : "true",
  },
  {
    "id" : "5",
    "name" : "Herbal Essences Argan Oil Shampoo",
    "price" : "₹ 355",
    "brand" : "Herbal Essence",
    "image" : "https://m.media-amazon.com/images/I/41RpujzemuL._SX300_SY300_QL70_FMwebp_.jpg",
    "Description" : "Argan Oil of Morocco SHAMPOO repairs damaged hair to leave them smoother and softer; Made up of 90% naturally derived ingredients*",
    "benefits" : "rafted with bio:renews blend of natural antioxidants, aloe and sea kelp (a natura source of essential nutrients)",
    "url" : "https://www.amazon.in/Herbal-Essences-bio-Morocco-Shampoo/dp/B07PB4G6RG/ref=sr_1_17?crid=24QDKNVQGNX8A&keywords=shampoo&qid=1707157301&s=beauty&sprefix=shampoo%2Cbeauty%2C194&sr=1-17&th=1",
    "category" : "Dandruff",
    "best seller" : "false",
  },
  {
    "id" : "6",
    "name" : "Plum Coconut Shampoo",
    "price" : "₹ 305",
    "brand" : "Plum Coconut",
    "image" : "https://m.media-amazon.com/images/I/31Jspe+pzbL._SY300_SX300_.jpg",
    "Description" : "Revitalize your hair with our products that enhance shine, strengthen strands, boost volume, retain moisture, and ensure a smooth, sleek finish. Experience the ultimate care for your hair's natural beauty.",
    "benefits" : "Unleash the brilliance of your hair with our transformative products. Discover the magic of enhanced shine, strengthened strands, added volume, superior moisture retention, and silky smoothness. Elevate your haircare routine to a new level, embracing a vibrant and healthy look that speaks volumes",
    "url" : "https://www.amazon.in/Plum-Peptides-strength-strengthens-Paraben-Free/dp/B0BVZ68BPQ/ref=sr_1_18?crid=24QDKNVQGNX8A&keywords=shampoo&qid=1707157301&s=beauty&sprefix=shampoo%2Cbeauty%2C194&sr=1-18",
    "category" : "Dandruff",
    "best seller" : "true",
  },
  {
    "id" : "7",
    "name" : "Herbal Essences Shampoo",
    "price" : "₹ 461",
    "brand" : "Herbal Essence",
    "image" : "https://m.media-amazon.com/images/I/41ufuJEhrPL._SX300_SY300_QL70_FMwebp_.jpg",
    "Description" : "Argan Oil of Morocco SHAMPOO repairs damaged hair to leave them smoother and softer; Made up of 90% naturally derived ingredients*",
    "benefits" : "rafted with bio:renews blend of natural antioxidants, aloe and sea kelp (a natura source of essential nutrients)",
    "url" : "https://www.amazon.in/Herbal-Essences-Hydrate-Coconut-Shampoo/dp/B072ZN4LH5/ref=sr_1_43?crid=24QDKNVQGNX8A&keywords=shampoo&qid=1707157301&s=beauty&sprefix=shampoo%2Cbeauty%2C194&sr=1-43",
    "category" : "Hair Masks",
    "best seller" : "true",
  },
  {
    "id" : "8",
    "name" : "TRESemme Hair Fall Shampoo",
    "price" : "₹ 820",
    "brand" : "TRESemme Shampoo",
    "image" : "https://m.media-amazon.com/images/I/41DVwYcxp4L._SX300_SY300_QL70_FMwebp_.jpg",
    "Description" : "Fortify your hair against breakage and promote strength with our specialized hair care solution. Experience the confidence of longer and stronger locks, as our formula is designed to prevent hair fall due to breakage.",
    "benefits" : "Soothing Hydration: Experience the enchantment of Aloe Vera Extract, offering calming hydration to the scalp and reducing scalp irritation for a comfortable cleansing experience.",
    "url" : "https://www.amazon.in/TRESemme-Defence-Shampoo-Keratin-Stronger/dp/B07L3YNL2V/ref=sr_1_2?crid=31D1C933HO8J2&keywords=tresemme+shampoo&qid=1707227433&s=beauty&sprefix=Tress%2Cbeauty%2C183&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    "category" : "Hairfall",
    "best seller" : "false",
  },
  {
    "id" : "9",
    "name" : "Thrive Anti-Dandruff Shampoo",
    "price" : "₹ 579",
    "brand" : "Thrive Shampoo",
    "image" : "https://m.media-amazon.com/images/I/61fhDBp95jL._SX425_.jpg",
    "Description" : "CUSTOMISED HAIR CARE REGIMEN TO SUIT DRY SCALP & WAVY HAIR: Safe and effective hair care regimen for dry scalp & wavy hair with hair fall. Includes a set of 2 products - Shampoo & Conditioner 200ml each; Reduces hair fall within 2-3 weeks.",
    "benefits" : "Anti-frizz,Breakage,Deep Conditioning,Hydrating,Moisturizing,Nourishing,Softening,Strengthening",
    "url" : "https://www.amazon.in/ThriveCo-Anti-Dandruff-Pre-Shampoo-Treatment-Dandruff/dp/B08NVCF9SW/ref=sr_1_25?crid=XOLZVMP7ER5Y&keywords=anti+dandruff&qid=1707225772&s=beauty&sprefix=anti+dandruff%2Cbeauty%2C183&sr=1-25",
    "category" : "Dandruff",
    "best seller" : "true",
  },
  {
    "id" : "10",
    "name" : "Biotoin Collagen Hair Mask",
    "price" : "₹ 470",
    "brand" : "Biotin Hair Mask",
    "image" : "https://m.media-amazon.com/images/I/61cfb52juTL._SX425_.jpg",
    "Description" : "Hair Growth is not a Dream anymore: A hair care recipe that is years old will produce outstanding effects and encourage hair growth. Increased hair growth results from the oils in the shampoo penetrating deeply into the roots and stimulating the hair follicles.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/St-Botanica-Collagen-Nourish-Parabens-Sulphates/dp/B08LBPN757/ref=sr_1_2?crid=3966BCL4NN2TG&keywords=biotin+collagen+hair+mask&qid=1707227161&s=beauty&sprefix=biotin+collagen+hair+mask%2Cbeauty%2C188&sr=1-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    "category" : "Hair Masks",
    "best seller" : "true",
  },
  {
    "id" : "11",
    "name" : "WoW Hair Growth Oil",
    "price" : "₹ 533",
    "brand" : "Wow HairCare",
    "image" : "https://m.media-amazon.com/images/I/61++TXBLMrL._SX425_.jpg",
    "Description" : "Argan Oil of Morocco SHAMPOO repairs damaged hair to leave them smoother and softer; Made up of 90% naturally derived ingredients*",
    "benefits" : "rafted with bio:renews blend of natural antioxidants, aloe and sea kelp (a natura source of essential nutrients)",
    "url" : "https://www.amazon.in/WOW-Skin-Science-Rosemary-Stimulates/dp/B0CCHV3J5W/ref=sr_1_3?crid=1EP6JFQEJ929B&keywords=hair+growth&qid=1707225973&s=beauty&sprefix=hair+growth%2Cbeauty%2C200&sr=1-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    "category" : "Volumize",
    "best seller" : "false",
  },
  {
    "id" : "12",
    "name" : "PILGRIM Argan Oil Hair Mask",
    "price" : "₹ 584",
    "brand" : "PILGRIM Hair Mask",
    "image" : "https://m.media-amazon.com/images/I/61mCMw6lahL._SL1500_.jpg",
    "Description" : "HERBAL HAIR MASK & PACK TO REDUCE HAIRFALL, PROMOTE GROWTH: Our premium Argan Oil Hair Mask is an essential step in your hair care regime to provide deep conditioning. It moisturzies the scalp & nourishes the roots to reduce itching. The hydrating oils of White Lotus & Camellia stimulates the hair follicles, repairs dry, damaged, frizzy hair, reduces hairfall, promotes hair growth, enhances volume and softer, silkier & shinier hair. It is sulphate free, paraben free, mineral oil free",
    "benefits" : "This perfect blend of natural ingredients is the answer to all your questions about hair damage control; whether its from excess styling, blow drying, flat ironing or sun exposure. It helps in strengthening hair (by working on Keratin), reducing frizz & split ends, moisturizing and imparting softness. Goodbye dull & damaged hair; Hello shiny & strong hair!",
    "url" : "https://www.amazon.in/Pilgrim-Camellia-smoothening-conditioning-control/dp/B09PHCH19D/ref=sr_1_6?crid=1GKFUKM40UA9C&keywords=hair%2Bmasks&qid=1707311358&sprefix=hair%2Bmasks%2Caps%2C217&sr=8-6&th=1",
    "category" : "Hair Masks",
    "best seller" : "true",
  },
  {
    "id" : "13",
    "name" : "Biotique Argan Oil Hair Mask",
    "price" : "₹ 163",
    "brand" : "Biotique Hair Mask",
    "image" : "https://m.media-amazon.com/images/I/61juqUQgxUL._SL1200_.jpg",
    "Description" : "ARGAN HAIR MASK TO REDUCE HAIRFALL- Argan oil is proven to make hair softer, silkier and shinier. It is the ideal hair conditioner, and it can even help to treat split ends and tame frizzy hair. It also prevents hair fall and promotes hair growth.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Biotique-Argan-Morocco-Ideal-Stronger/dp/B08JR5MDJ3/ref=sr_1_3_sspa?crid=D20XKP501KP0&keywords=hair%2Bmasks&qid=1707311547&sprefix=hair%2Bmasks%2Caps%2C270&sr=8-3-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    "category" : "Hair Masks",
    "best seller" : "true",
  },
  {
    "id" : "14",
    "name" : "Arata Anti Dandruff Shampoo",
    "price" : "₹ 1249",
    "brand" : "Arata Shampoo",
    "image" : "https://m.media-amazon.com/images/I/617kYsFUS3L._SL1500_.jpg",
    "Description" : "GENTLY CLEANSES: The shampoo boasts an effective formula that gently cleanses your scalp while taking care of the flaky situation.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Arata-Anti-Dandruff-Recovery-Flakiness-Moisturizes/dp/B0B7X57283/ref=sr_1_39?crid=1NGL4HOWQMFJ7&keywords=anti+dandruff+products&qid=1707311984&sprefix=anti+dandruff+products%2Caps%2C202&sr=8-39",
    "category" : "Dandruff",
    "best seller" : "true",
  },
  {
    "id" : "15",
    "name" : "Loreal Advanced Volumising Shampoo",
    "price" : "₹ 745",
    "brand" : "Loreal Shampoo",
    "image" : "https://m.media-amazon.com/images/I/518Id1c9IiL._SL1500_.jpg",
    "Description" : "Hair Growth is not a Dream anymore: A hair care recipe that is years old will produce outstanding effects and encourage hair growth. Increased hair growth results from the oils in the shampoo penetrating deeply into the roots and stimulating the hair follicles.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/LOr%C3%A9al-Professionnel-Advanced-Density-Thinning/dp/B0BQJMKZCR/ref=sr_1_1_sspa?crid=2AP9GE0W1ZHKA&keywords=volumizing+shampoo&qid=1707312235&sprefix=volumi%2Caps%2C193&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    "category" : "Volumize",
    "best seller" : "true",
  },
  {
    "id" : "16",
    "name" : "Clensta Hair Fall Shampoo",
    "price" : "₹ 261",
    "brand" : "Clensta Shampoo",
    "image" : "https://m.media-amazon.com/images/I/61H4ooYNgfL._SL1500_.jpg",
    "Description" : "Strengthen and Thicken: Rosemary stimulates hair growth and combats premature graying, while Biotin strengthens hair, reducing breakage, and enhancing thickness.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Clensta-Rosemary-Control-Reducing-Breakage/dp/B0CRRWBFHH/ref=sr_1_2_sspa?crid=3FPSYEPGCOXY4&keywords=haircare+products&qid=1707497850&sprefix=haircare+products%2Caps%2C231&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    "category" : "Hairfall",
    "best seller" : "true",
  },
  {
    "id" : "17",
    "name" : "Man Matters Biotin Hair Gummies",
    "price" : "₹ 799",
    "brand" : "Man Matters",
    "image" : "https://m.media-amazon.com/images/I/81k4lLr30vL._SL1500_.jpg",
    "Description" : "GIVES THE RIGHT NUTRITION: Man Matters Biotin Gummies are formulated with of pure easily absorbable Biotin that is rich in fatty acids & powerful antioxidants that give your hair the right nutrition. Gummies promote fast and proper absorption of the nutrients, resulting in improved health of your hair.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Man-Matters-Strawberry-Flavoured-Vegetarian/dp/B098F3HYJR/ref=sr_1_5?crid=3IAF5EV33RIFZ&keywords=man%2Bmatters&qid=1707498116&sprefix=man%2Bmatter%2Caps%2C190&sr=8-5&th=1",
    "category" : "Hairfall",
    "best seller" : "false",
  },
  {
    "id" : "18",
    "name" : "Vedix Hairfall Control",
    "price" : "₹ 1299",
    "brand" : "Vedix Shampoo",
    "image" : "https://m.media-amazon.com/images/I/61YSqLa3wML._SL1000_.jpg",
    "Description" : "CUSTOMISED AYURVEDIC HAIR CARE REGIMEN TO SUIT NORMAL/OILY HAIR WITH NORMAL-OILY SCALP & WAVY HAIR: Safe and effective hair care regimen for normal/oily hair with dry scalp & straight hair with hair fall. Includes a set of 3 products - Hair Oil, Shampoo and Hair Serum; Reduce hair fall within 4 - 6 weeks.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Vedix-Customized-Control-Regimen-Normal/dp/B092QDVV9Y/ref=sr_1_27?crid=3FPSYEPGCOXY4&keywords=haircare+products&qid=1707497850&sprefix=haircare+products%2Caps%2C231&sr=8-27",
    "category" : "Hairfall",
    "best seller" : "false",
  },
  {
    "id" : "19",
    "name" : "Zandu Hair Growth Vitalizer",
    "price" : "₹ 336",
    "brand" : "Zandu Hair Growth",
    "image" : "https://m.media-amazon.com/images/I/71JbRQ7KVBL._SL1500_.jpg",
    "Description" : "Helps to Prevent Hair Fall: This Ayurvedic hair vitalizer has been carefully formulated with ingredients that play an important role in maintaining hair health. It can help to retain nutrition in your scalp and can therefore help mitigate hair fall in the long run.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Zandu-Vitalizer-Formulation-Prepared-Nourishing/dp/B09XJ4JZV6/ref=sr_1_26?crid=3FPSYEPGCOXY4&keywords=haircare+products&qid=1707497850&sprefix=haircare+products%2Caps%2C231&sr=8-26",
    "category" : "Volumize",
    "best seller" : "false",
  },
  {
    "id" : "20",
    "name" : "Arata Styling Hair Cream",
    "price" : "₹ 419",
    "brand" : "Arata Hair Cream",
    "image" : "https://m.media-amazon.com/images/I/51FrcwLZXaL._SL1080_.jpg",
    "Description" : "ALL-NATURAL STYLING & HOLD: Packed with the natural goodness of organic flaxseed and olive extracts, our hair cream and hair gel combo is great for everyday styling and sculpting. The formulations are water soluble and rinse out easily.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Arata-Natural-defining-Styling-Nourishing/dp/B08JCXJZJB/ref=sr_1_18?crid=289MZNQWNLLFJ&keywords=Arata&qid=1707498551&sprefix=arata%2Caps%2C277&sr=8-18",
    "category" : "Dandruff",
    "best seller" : "false",
  },
  {
    "id" : "21",
    "name" : "Arata Intensive Hair Fall Control",
    "price" : "₹ 1494",
    "brand" : "Arata Essentials",
    "image" : "https://m.media-amazon.com/images/I/61P03bPiT8S._SL1500_.jpg",
    "Description" : "Helps to Prevent Hair Fall: This Ayurvedic hair vitalizer has been carefully formulated with ingredients that play an important role in maintaining hair health. It can help to retain nutrition in your scalp and can therefore help mitigate hair fall in the long run.",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Arata-Intensive-Anti-Hairfall-Conditioner-Transparent/dp/B094Y65W6Q/ref=sr_1_2_sspa?crid=2QMCJXXPUN2MZ&keywords=Arata+Hair+growth&qid=1707499932&sprefix=arata+hair+growth%2Caps%2C262&sr=8-2-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1",
    "category" : "Hairfall",
    "best seller" : "true",
  },

  {
    "id" : "22",
    "name" : "Indulekha Bringha Hair Oil",
    "price" : "₹ 409",
    "brand" : "Indulekha Hair Oil",
    "image" : "https://m.media-amazon.com/images/I/61IxF1ljJHL._SL1000_.jpg",
    "Description" : "https://www.amazon.in/Indulekha-Bringha-Ayurvedic-Control-Bringharaj/dp/B00S850C5C/ref=sr_1_1_sspa?crid=2LCIG29YHL45Y&keywords=HAIR%2BOIL&qid=1707498903&sprefix=hair%2Boil%2Caps%2C235&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    "benefits" : "Relieves Dandruff & Itchy Scalp: The shampoo's time-tested Ayurveda ingredients make sure that the scalp is entirely cleansed and that the roots are stimulated, which reduces dandruff.",
    "url" : "https://www.amazon.in/Indulekha-Bringha-Ayurvedic-Control-Bringharaj/dp/B00S850C5C/ref=sr_1_1_sspa?crid=2LCIG29YHL45Y&keywords=HAIR%2BOIL&qid=1707498903&sprefix=hair%2Boil%2Caps%2C235&sr=8-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&th=1",
    "category" : "Dandruff",
    "best seller" : "false",
  },




];